@echo off
echo Buscando procesos en el puerto 8080...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8080" ^| find "LISTENING"') do taskkill /f /pid %%a
echo Reiniciando el servidor...
python server.py
pause
